# Generated by Django 4.2 on 2023-05-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='isFavorite',
            field=models.BooleanField(default=False),
        ),
    ]
