# Generated by Django 4.2 on 2023-05-09 22:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("behavio_app", "0002_question_isfavorite"),
    ]

    operations = [
        migrations.RenameField(
            model_name="favoritedquestion",
            old_name="Question",
            new_name="question",
        ),
        migrations.RenameField(
            model_name="feedback",
            old_name="Response",
            new_name="response",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="Category",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="response",
            old_name="Question",
            new_name="question",
        ),
    ]
