# Generated by Django 4.2 on 2023-05-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavio_app', '0003_rename_question_favoritedquestion_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='feedbackCounter',
            field=models.IntegerField(default=0),
        ),
    ]
