# Generated by Django 4.2 on 2023-05-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("behavio_app", "0004_response_feedbackcounter"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="question_text",
            field=models.CharField(blank=True, null=True),
        ),
    ]
